title: My Study Notes

collections:
  os:
    output: true
    permalink: /os/:name/

  network:
    output: true
    permalink: /network/:name/

  tools:
    output: true
    permalink: /tools/:name/

  CTF:
    output: true
    permalink: /CTF/:path/