title: My Study Notes

collections:
  os:
    output: true
    permalink: /os/:name/

  network:
    output: true
    permalink: /network/:name/

  crypto:
    output: true
    permalink: /crypto/:name/

  websec:
    output: true
    permalink: /websec/:name/